interface ZIF_I_SCARR_BOPF_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_SCARR_BOPF,
 CREATE_ZI_SCARR_BOPF           TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F666677',
 DELETE_ZI_SCARR_BOPF           TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F66E677',
 LOCK_ZI_SCARR_BOPF             TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F65A677',
 SAVE_ZI_SCARR_BOPF             TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F676677',
 UNLOCK_ZI_SCARR_BOPF           TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F65E677',
 UPDATE_ZI_SCARR_BOPF           TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F66A677',
 VALIDATE_ZI_SCARR_BOPF         TYPE /BOBF/ACT_KEY VALUE '0242AC1100031EEBBEB772936F672677',
      END OF ZI_SCARR_BOPF,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_SCARR_BOPF,
        BEGIN OF LOCK_ZI_SCARR_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZI_SCARR_BOPF,
        BEGIN OF UNLOCK_ZI_SCARR_BOPF,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZI_SCARR_BOPF,
      END OF ZI_SCARR_BOPF,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_SCARR_BOPF,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '0242AC1100031EEBBEB772936F684677',
      END OF ZI_SCARR_BOPF,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_SCARR_BOPF,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100031EEBBEB772936F658677',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100031EEBBEB772936F654677',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100031EEBBEB772936F664677',
      END OF ZI_SCARR_BOPF,
      BEGIN OF ZI_SCARR_BOPF_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100031EEBBEB772936F67C677',
      END OF ZI_SCARR_BOPF_LOCK,
      BEGIN OF ZI_SCARR_BOPF_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100031EEBBEB772936F67A677',
      END OF ZI_SCARR_BOPF_MESSAGE,
      BEGIN OF ZI_SCARR_BOPF_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '0242AC1100031EEBBEB772936F67E677',
      END OF ZI_SCARR_BOPF_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_SCARR_BOPF,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_SCARR_BOPF,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '0242AC1100031EEBBEB772936F64A677' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_SCARR_BOPF' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_SCARR_BOPF,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '0242AC1100031EEBBEB772936F686677',
      END OF ZI_SCARR_BOPF,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_SCARR_BOPF                  TYPE /BOBF/OBM_GROUP_KEY VALUE '0242AC1100031EEBBEB772936F6C4677',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_SCARR_BOPF                  TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100031EEBBEB772936F64E677',
 ZI_SCARR_BOPF_LOCK             TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100031EEBBEB772936F656677',
 ZI_SCARR_BOPF_MESSAGE          TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100031EEBBEB772936F652677',
 ZI_SCARR_BOPF_PROPERTY         TYPE /BOBF/OBM_NODE_KEY VALUE '0242AC1100031EEBBEB772936F662677',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_SCARR_BOPF,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CARRNAME                       TYPE STRING VALUE 'CARRNAME',
  CURRCODE                       TYPE STRING VALUE 'CURRCODE',
  URL                            TYPE STRING VALUE 'URL',
      END OF ZI_SCARR_BOPF,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_SCARR_BOPF,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '0242AC1100031EEBBEB772936F650677',
      END OF ZI_SCARR_BOPF,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_SCARR_BOPF,
 ALTKEY_UNIQUENESS_CHECK        TYPE /BOBF/VAL_KEY VALUE '0242AC1100031EEBBEB772936F68A677',
      END OF ZI_SCARR_BOPF,
    END OF SC_VALIDATION .
endinterface.
